-- soc_system_DMA_neurax_read.vhd

-- This file was auto-generated from altera_msgdma_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 1077

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity soc_system_DMA_neurax_read is
	port (
		mm_write_address             : out std_logic_vector(31 downto 0);                     --         mm_write.address
		mm_write_write               : out std_logic;                                         --                 .write
		mm_write_byteenable          : out std_logic_vector(3 downto 0);                      --                 .byteenable
		mm_write_writedata           : out std_logic_vector(31 downto 0);                     --                 .writedata
		mm_write_waitrequest         : in  std_logic                      := '0';             --                 .waitrequest
		clock_clk                    : in  std_logic                      := '0';             --            clock.clk
		reset_n_reset_n              : in  std_logic                      := '0';             --          reset_n.reset_n
		csr_writedata                : in  std_logic_vector(31 downto 0)  := (others => '0'); --              csr.writedata
		csr_write                    : in  std_logic                      := '0';             --                 .write
		csr_byteenable               : in  std_logic_vector(3 downto 0)   := (others => '0'); --                 .byteenable
		csr_readdata                 : out std_logic_vector(31 downto 0);                     --                 .readdata
		csr_read                     : in  std_logic                      := '0';             --                 .read
		csr_address                  : in  std_logic_vector(2 downto 0)   := (others => '0'); --                 .address
		descriptor_slave_write       : in  std_logic                      := '0';             -- descriptor_slave.write
		descriptor_slave_waitrequest : out std_logic;                                         --                 .waitrequest
		descriptor_slave_writedata   : in  std_logic_vector(127 downto 0) := (others => '0'); --                 .writedata
		descriptor_slave_byteenable  : in  std_logic_vector(15 downto 0)  := (others => '0'); --                 .byteenable
		csr_irq_irq                  : out std_logic;                                         --          csr_irq.irq
		st_sink_data                 : in  std_logic_vector(31 downto 0)  := (others => '0'); --          st_sink.data
		st_sink_valid                : in  std_logic                      := '0';             --                 .valid
		st_sink_ready                : out std_logic;                                         --                 .ready
		st_sink_error                : in  std_logic                      := '0'              --                 .error
	);
end entity soc_system_DMA_neurax_read;

architecture rtl of soc_system_DMA_neurax_read is
	component dispatcher is
		generic (
			MODE                        : integer := 0;
			RESPONSE_PORT               : integer := 0;
			DESCRIPTOR_INTERFACE        : integer := 0;
			DESCRIPTOR_FIFO_DEPTH       : integer := 128;
			ENHANCED_FEATURES           : integer := 1;
			DESCRIPTOR_WIDTH            : integer := 256;
			DESCRIPTOR_BYTEENABLE_WIDTH : integer := 32
		);
		port (
			clk                     : in  std_logic                      := 'X';             -- clk
			reset                   : in  std_logic                      := 'X';             -- reset
			csr_writedata           : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			csr_write               : in  std_logic                      := 'X';             -- write
			csr_byteenable          : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			csr_readdata            : out std_logic_vector(31 downto 0);                     -- readdata
			csr_read                : in  std_logic                      := 'X';             -- read
			csr_address             : in  std_logic_vector(2 downto 0)   := (others => 'X'); -- address
			descriptor_write        : in  std_logic                      := 'X';             -- write
			descriptor_waitrequest  : out std_logic;                                         -- waitrequest
			descriptor_writedata    : in  std_logic_vector(127 downto 0) := (others => 'X'); -- writedata
			descriptor_byteenable   : in  std_logic_vector(15 downto 0)  := (others => 'X'); -- byteenable
			src_write_master_data   : out std_logic_vector(255 downto 0);                    -- data
			src_write_master_valid  : out std_logic;                                         -- valid
			src_write_master_ready  : in  std_logic                      := 'X';             -- ready
			snk_write_master_data   : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_write_master_valid  : in  std_logic                      := 'X';             -- valid
			snk_write_master_ready  : out std_logic;                                         -- ready
			csr_irq                 : out std_logic;                                         -- irq
			src_response_data       : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid      : out std_logic;                                         -- valid
			src_response_ready      : in  std_logic                      := 'X';             -- ready
			snk_descriptor_data     : in  std_logic_vector(127 downto 0) := (others => 'X'); -- data
			snk_descriptor_valid    : in  std_logic                      := 'X';             -- valid
			snk_descriptor_ready    : out std_logic;                                         -- ready
			mm_response_waitrequest : out std_logic;                                         -- waitrequest
			mm_response_byteenable  : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			mm_response_address     : in  std_logic                      := 'X';             -- address
			mm_response_readdata    : out std_logic_vector(31 downto 0);                     -- readdata
			mm_response_read        : in  std_logic                      := 'X';             -- read
			src_read_master_data    : out std_logic_vector(255 downto 0);                    -- data
			src_read_master_valid   : out std_logic;                                         -- valid
			src_read_master_ready   : in  std_logic                      := 'X';             -- ready
			snk_read_master_data    : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_read_master_valid   : in  std_logic                      := 'X';             -- valid
			snk_read_master_ready   : out std_logic                                          -- ready
		);
	end component dispatcher;

	component write_master is
		generic (
			DATA_WIDTH                     : integer := 32;
			LENGTH_WIDTH                   : integer := 32;
			FIFO_DEPTH                     : integer := 32;
			STRIDE_ENABLE                  : integer := 0;
			BURST_ENABLE                   : integer := 0;
			PACKET_ENABLE                  : integer := 0;
			ERROR_ENABLE                   : integer := 0;
			ERROR_WIDTH                    : integer := 8;
			BYTE_ENABLE_WIDTH              : integer := 4;
			BYTE_ENABLE_WIDTH_LOG2         : integer := 2;
			ADDRESS_WIDTH                  : integer := 32;
			FIFO_DEPTH_LOG2                : integer := 5;
			SYMBOL_WIDTH                   : integer := 8;
			NUMBER_OF_SYMBOLS              : integer := 4;
			NUMBER_OF_SYMBOLS_LOG2         : integer := 2;
			MAX_BURST_COUNT_WIDTH          : integer := 2;
			UNALIGNED_ACCESSES_ENABLE      : integer := 0;
			ONLY_FULL_ACCESS_ENABLE        : integer := 0;
			BURST_WRAPPING_SUPPORT         : integer := 1;
			PROGRAMMABLE_BURST_ENABLE      : integer := 0;
			MAX_BURST_COUNT                : integer := 2;
			FIFO_SPEED_OPTIMIZATION        : integer := 1;
			STRIDE_WIDTH                   : integer := 1;
			ACTUAL_BYTES_TRANSFERRED_WIDTH : integer := 32
		);
		port (
			clk                : in  std_logic                      := 'X';             -- clk
			reset              : in  std_logic                      := 'X';             -- reset
			master_address     : out std_logic_vector(31 downto 0);                     -- address
			master_write       : out std_logic;                                         -- write
			master_byteenable  : out std_logic_vector(3 downto 0);                      -- byteenable
			master_writedata   : out std_logic_vector(31 downto 0);                     -- writedata
			master_waitrequest : in  std_logic                      := 'X';             -- waitrequest
			snk_data           : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- data
			snk_valid          : in  std_logic                      := 'X';             -- valid
			snk_ready          : out std_logic;                                         -- ready
			snk_error          : in  std_logic                      := 'X';             -- error
			snk_command_data   : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_command_valid  : in  std_logic                      := 'X';             -- valid
			snk_command_ready  : out std_logic;                                         -- ready
			src_response_data  : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid : out std_logic;                                         -- valid
			src_response_ready : in  std_logic                      := 'X';             -- ready
			master_burstcount  : out std_logic_vector(0 downto 0);                      -- burstcount
			snk_sop            : in  std_logic                      := 'X';             -- startofpacket
			snk_eop            : in  std_logic                      := 'X';             -- endofpacket
			snk_empty          : in  std_logic_vector(1 downto 0)   := (others => 'X')  -- empty
		);
	end component write_master;

	signal dispatcher_internal_write_command_source_valid : std_logic;                      -- dispatcher_internal:src_write_master_valid -> write_mstr_internal:snk_command_valid
	signal dispatcher_internal_write_command_source_data  : std_logic_vector(255 downto 0); -- dispatcher_internal:src_write_master_data -> write_mstr_internal:snk_command_data
	signal dispatcher_internal_write_command_source_ready : std_logic;                      -- write_mstr_internal:snk_command_ready -> dispatcher_internal:src_write_master_ready
	signal write_mstr_internal_response_source_valid      : std_logic;                      -- write_mstr_internal:src_response_valid -> dispatcher_internal:snk_write_master_valid
	signal write_mstr_internal_response_source_data       : std_logic_vector(255 downto 0); -- write_mstr_internal:src_response_data -> dispatcher_internal:snk_write_master_data
	signal write_mstr_internal_response_source_ready      : std_logic;                      -- dispatcher_internal:snk_write_master_ready -> write_mstr_internal:src_response_ready
	signal reset_n_reset_n_ports_inv                      : std_logic;                      -- reset_n_reset_n:inv -> [dispatcher_internal:reset, write_mstr_internal:reset]

begin

	dispatcher_internal : component dispatcher
		generic map (
			MODE                        => 2,
			RESPONSE_PORT               => 2,
			DESCRIPTOR_INTERFACE        => 0,
			DESCRIPTOR_FIFO_DEPTH       => 128,
			ENHANCED_FEATURES           => 0,
			DESCRIPTOR_WIDTH            => 128,
			DESCRIPTOR_BYTEENABLE_WIDTH => 16
		)
		port map (
			clk                     => clock_clk,                                                                                                                                                                                                                                                          --                clock.clk
			reset                   => reset_n_reset_n_ports_inv,                                                                                                                                                                                                                                          --          clock_reset.reset
			csr_writedata           => csr_writedata,                                                                                                                                                                                                                                                      --                  CSR.writedata
			csr_write               => csr_write,                                                                                                                                                                                                                                                          --                     .write
			csr_byteenable          => csr_byteenable,                                                                                                                                                                                                                                                     --                     .byteenable
			csr_readdata            => csr_readdata,                                                                                                                                                                                                                                                       --                     .readdata
			csr_read                => csr_read,                                                                                                                                                                                                                                                           --                     .read
			csr_address             => csr_address,                                                                                                                                                                                                                                                        --                     .address
			descriptor_write        => descriptor_slave_write,                                                                                                                                                                                                                                             --     Descriptor_Slave.write
			descriptor_waitrequest  => descriptor_slave_waitrequest,                                                                                                                                                                                                                                       --                     .waitrequest
			descriptor_writedata    => descriptor_slave_writedata,                                                                                                                                                                                                                                         --                     .writedata
			descriptor_byteenable   => descriptor_slave_byteenable,                                                                                                                                                                                                                                        --                     .byteenable
			src_write_master_data   => dispatcher_internal_write_command_source_data,                                                                                                                                                                                                                      -- Write_Command_Source.data
			src_write_master_valid  => dispatcher_internal_write_command_source_valid,                                                                                                                                                                                                                     --                     .valid
			src_write_master_ready  => dispatcher_internal_write_command_source_ready,                                                                                                                                                                                                                     --                     .ready
			snk_write_master_data   => write_mstr_internal_response_source_data,                                                                                                                                                                                                                           --  Write_Response_Sink.data
			snk_write_master_valid  => write_mstr_internal_response_source_valid,                                                                                                                                                                                                                          --                     .valid
			snk_write_master_ready  => write_mstr_internal_response_source_ready,                                                                                                                                                                                                                          --                     .ready
			csr_irq                 => csr_irq_irq,                                                                                                                                                                                                                                                        --              csr_irq.irq
			src_response_data       => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_response_valid      => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_response_ready      => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_descriptor_data     => "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",                                                                                                                                 --          (terminated)
			snk_descriptor_valid    => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_descriptor_ready    => open,                                                                                                                                                                                                                                                               --          (terminated)
			mm_response_waitrequest => open,                                                                                                                                                                                                                                                               --          (terminated)
			mm_response_byteenable  => "0000",                                                                                                                                                                                                                                                             --          (terminated)
			mm_response_address     => '0',                                                                                                                                                                                                                                                                --          (terminated)
			mm_response_readdata    => open,                                                                                                                                                                                                                                                               --          (terminated)
			mm_response_read        => '0',                                                                                                                                                                                                                                                                --          (terminated)
			src_read_master_data    => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_read_master_valid   => open,                                                                                                                                                                                                                                                               --          (terminated)
			src_read_master_ready   => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_read_master_data    => "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", --          (terminated)
			snk_read_master_valid   => '0',                                                                                                                                                                                                                                                                --          (terminated)
			snk_read_master_ready   => open                                                                                                                                                                                                                                                                --          (terminated)
		);

	write_mstr_internal : component write_master
		generic map (
			DATA_WIDTH                     => 32,
			LENGTH_WIDTH                   => 18,
			FIFO_DEPTH                     => 32,
			STRIDE_ENABLE                  => 0,
			BURST_ENABLE                   => 0,
			PACKET_ENABLE                  => 0,
			ERROR_ENABLE                   => 1,
			ERROR_WIDTH                    => 1,
			BYTE_ENABLE_WIDTH              => 4,
			BYTE_ENABLE_WIDTH_LOG2         => 2,
			ADDRESS_WIDTH                  => 32,
			FIFO_DEPTH_LOG2                => 5,
			SYMBOL_WIDTH                   => 8,
			NUMBER_OF_SYMBOLS              => 4,
			NUMBER_OF_SYMBOLS_LOG2         => 2,
			MAX_BURST_COUNT_WIDTH          => 1,
			UNALIGNED_ACCESSES_ENABLE      => 0,
			ONLY_FULL_ACCESS_ENABLE        => 1,
			BURST_WRAPPING_SUPPORT         => 0,
			PROGRAMMABLE_BURST_ENABLE      => 0,
			MAX_BURST_COUNT                => 1,
			FIFO_SPEED_OPTIMIZATION        => 1,
			STRIDE_WIDTH                   => 1,
			ACTUAL_BYTES_TRANSFERRED_WIDTH => 32
		)
		port map (
			clk                => clock_clk,                                      --             Clock.clk
			reset              => reset_n_reset_n_ports_inv,                      --       Clock_reset.reset
			master_address     => mm_write_address,                               -- Data_Write_Master.address
			master_write       => mm_write_write,                                 --                  .write
			master_byteenable  => mm_write_byteenable,                            --                  .byteenable
			master_writedata   => mm_write_writedata,                             --                  .writedata
			master_waitrequest => mm_write_waitrequest,                           --                  .waitrequest
			snk_data           => st_sink_data,                                   --         Data_Sink.data
			snk_valid          => st_sink_valid,                                  --                  .valid
			snk_ready          => st_sink_ready,                                  --                  .ready
			snk_error          => st_sink_error,                                  --                  .error
			snk_command_data   => dispatcher_internal_write_command_source_data,  --      Command_Sink.data
			snk_command_valid  => dispatcher_internal_write_command_source_valid, --                  .valid
			snk_command_ready  => dispatcher_internal_write_command_source_ready, --                  .ready
			src_response_data  => write_mstr_internal_response_source_data,       --   Response_Source.data
			src_response_valid => write_mstr_internal_response_source_valid,      --                  .valid
			src_response_ready => write_mstr_internal_response_source_ready,      --                  .ready
			master_burstcount  => open,                                           --       (terminated)
			snk_sop            => '0',                                            --       (terminated)
			snk_eop            => '0',                                            --       (terminated)
			snk_empty          => "00"                                            --       (terminated)
		);

	reset_n_reset_n_ports_inv <= not reset_n_reset_n;

end architecture rtl; -- of soc_system_DMA_neurax_read
