-- soc_system_DMA_neurax_write.vhd

-- This file was auto-generated from altera_msgdma_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 1077

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity soc_system_DMA_neurax_write is
	port (
		mm_read_address              : out std_logic_vector(31 downto 0);                     --          mm_read.address
		mm_read_read                 : out std_logic;                                         --                 .read
		mm_read_byteenable           : out std_logic_vector(3 downto 0);                      --                 .byteenable
		mm_read_readdata             : in  std_logic_vector(31 downto 0)  := (others => '0'); --                 .readdata
		mm_read_waitrequest          : in  std_logic                      := '0';             --                 .waitrequest
		mm_read_readdatavalid        : in  std_logic                      := '0';             --                 .readdatavalid
		clock_clk                    : in  std_logic                      := '0';             --            clock.clk
		reset_n_reset_n              : in  std_logic                      := '0';             --          reset_n.reset_n
		csr_writedata                : in  std_logic_vector(31 downto 0)  := (others => '0'); --              csr.writedata
		csr_write                    : in  std_logic                      := '0';             --                 .write
		csr_byteenable               : in  std_logic_vector(3 downto 0)   := (others => '0'); --                 .byteenable
		csr_readdata                 : out std_logic_vector(31 downto 0);                     --                 .readdata
		csr_read                     : in  std_logic                      := '0';             --                 .read
		csr_address                  : in  std_logic_vector(2 downto 0)   := (others => '0'); --                 .address
		descriptor_slave_write       : in  std_logic                      := '0';             -- descriptor_slave.write
		descriptor_slave_waitrequest : out std_logic;                                         --                 .waitrequest
		descriptor_slave_writedata   : in  std_logic_vector(127 downto 0) := (others => '0'); --                 .writedata
		descriptor_slave_byteenable  : in  std_logic_vector(15 downto 0)  := (others => '0'); --                 .byteenable
		csr_irq_irq                  : out std_logic;                                         --          csr_irq.irq
		st_source_data               : out std_logic_vector(31 downto 0);                     --        st_source.data
		st_source_valid              : out std_logic;                                         --                 .valid
		st_source_ready              : in  std_logic                      := '0';             --                 .ready
		st_source_error              : out std_logic;                                         --                 .error
		st_source_channel            : out std_logic                                          --                 .channel
	);
end entity soc_system_DMA_neurax_write;

architecture rtl of soc_system_DMA_neurax_write is
	component dispatcher is
		generic (
			MODE                        : integer := 0;
			RESPONSE_PORT               : integer := 0;
			DESCRIPTOR_INTERFACE        : integer := 0;
			DESCRIPTOR_FIFO_DEPTH       : integer := 128;
			ENHANCED_FEATURES           : integer := 1;
			DESCRIPTOR_WIDTH            : integer := 256;
			DESCRIPTOR_BYTEENABLE_WIDTH : integer := 32
		);
		port (
			clk                     : in  std_logic                      := 'X';             -- clk
			reset                   : in  std_logic                      := 'X';             -- reset
			csr_writedata           : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			csr_write               : in  std_logic                      := 'X';             -- write
			csr_byteenable          : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			csr_readdata            : out std_logic_vector(31 downto 0);                     -- readdata
			csr_read                : in  std_logic                      := 'X';             -- read
			csr_address             : in  std_logic_vector(2 downto 0)   := (others => 'X'); -- address
			descriptor_write        : in  std_logic                      := 'X';             -- write
			descriptor_waitrequest  : out std_logic;                                         -- waitrequest
			descriptor_writedata    : in  std_logic_vector(127 downto 0) := (others => 'X'); -- writedata
			descriptor_byteenable   : in  std_logic_vector(15 downto 0)  := (others => 'X'); -- byteenable
			src_read_master_data    : out std_logic_vector(255 downto 0);                    -- data
			src_read_master_valid   : out std_logic;                                         -- valid
			src_read_master_ready   : in  std_logic                      := 'X';             -- ready
			snk_read_master_data    : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_read_master_valid   : in  std_logic                      := 'X';             -- valid
			snk_read_master_ready   : out std_logic;                                         -- ready
			csr_irq                 : out std_logic;                                         -- irq
			src_response_data       : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid      : out std_logic;                                         -- valid
			src_response_ready      : in  std_logic                      := 'X';             -- ready
			snk_descriptor_data     : in  std_logic_vector(127 downto 0) := (others => 'X'); -- data
			snk_descriptor_valid    : in  std_logic                      := 'X';             -- valid
			snk_descriptor_ready    : out std_logic;                                         -- ready
			mm_response_waitrequest : out std_logic;                                         -- waitrequest
			mm_response_byteenable  : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			mm_response_address     : in  std_logic                      := 'X';             -- address
			mm_response_readdata    : out std_logic_vector(31 downto 0);                     -- readdata
			mm_response_read        : in  std_logic                      := 'X';             -- read
			src_write_master_data   : out std_logic_vector(255 downto 0);                    -- data
			src_write_master_valid  : out std_logic;                                         -- valid
			src_write_master_ready  : in  std_logic                      := 'X';             -- ready
			snk_write_master_data   : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_write_master_valid  : in  std_logic                      := 'X';             -- valid
			snk_write_master_ready  : out std_logic                                          -- ready
		);
	end component dispatcher;

	component read_master is
		generic (
			DATA_WIDTH                : integer := 32;
			LENGTH_WIDTH              : integer := 32;
			FIFO_DEPTH                : integer := 32;
			STRIDE_ENABLE             : integer := 0;
			BURST_ENABLE              : integer := 0;
			PACKET_ENABLE             : integer := 0;
			ERROR_ENABLE              : integer := 0;
			ERROR_WIDTH               : integer := 8;
			CHANNEL_ENABLE            : integer := 0;
			CHANNEL_WIDTH             : integer := 8;
			BYTE_ENABLE_WIDTH         : integer := 4;
			BYTE_ENABLE_WIDTH_LOG2    : integer := 2;
			ADDRESS_WIDTH             : integer := 32;
			FIFO_DEPTH_LOG2           : integer := 5;
			SYMBOL_WIDTH              : integer := 8;
			NUMBER_OF_SYMBOLS         : integer := 4;
			NUMBER_OF_SYMBOLS_LOG2    : integer := 2;
			MAX_BURST_COUNT_WIDTH     : integer := 2;
			UNALIGNED_ACCESSES_ENABLE : integer := 0;
			ONLY_FULL_ACCESS_ENABLE   : integer := 0;
			BURST_WRAPPING_SUPPORT    : integer := 1;
			PROGRAMMABLE_BURST_ENABLE : integer := 0;
			MAX_BURST_COUNT           : integer := 2;
			FIFO_SPEED_OPTIMIZATION   : integer := 1;
			STRIDE_WIDTH              : integer := 1
		);
		port (
			clk                  : in  std_logic                      := 'X';             -- clk
			reset                : in  std_logic                      := 'X';             -- reset
			master_address       : out std_logic_vector(31 downto 0);                     -- address
			master_read          : out std_logic;                                         -- read
			master_byteenable    : out std_logic_vector(3 downto 0);                      -- byteenable
			master_readdata      : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- readdata
			master_waitrequest   : in  std_logic                      := 'X';             -- waitrequest
			master_readdatavalid : in  std_logic                      := 'X';             -- readdatavalid
			src_data             : out std_logic_vector(31 downto 0);                     -- data
			src_valid            : out std_logic;                                         -- valid
			src_ready            : in  std_logic                      := 'X';             -- ready
			src_error            : out std_logic;                                         -- error
			src_channel          : out std_logic;                                         -- channel
			snk_command_data     : in  std_logic_vector(255 downto 0) := (others => 'X'); -- data
			snk_command_valid    : in  std_logic                      := 'X';             -- valid
			snk_command_ready    : out std_logic;                                         -- ready
			src_response_data    : out std_logic_vector(255 downto 0);                    -- data
			src_response_valid   : out std_logic;                                         -- valid
			src_response_ready   : in  std_logic                      := 'X';             -- ready
			master_burstcount    : out std_logic_vector(0 downto 0);                      -- burstcount
			src_sop              : out std_logic;                                         -- startofpacket
			src_eop              : out std_logic;                                         -- endofpacket
			src_empty            : out std_logic_vector(1 downto 0)                       -- empty
		);
	end component read_master;

	signal dispatcher_internal_read_command_source_valid : std_logic;                      -- dispatcher_internal:src_read_master_valid -> read_mstr_internal:snk_command_valid
	signal dispatcher_internal_read_command_source_data  : std_logic_vector(255 downto 0); -- dispatcher_internal:src_read_master_data -> read_mstr_internal:snk_command_data
	signal dispatcher_internal_read_command_source_ready : std_logic;                      -- read_mstr_internal:snk_command_ready -> dispatcher_internal:src_read_master_ready
	signal read_mstr_internal_response_source_valid      : std_logic;                      -- read_mstr_internal:src_response_valid -> dispatcher_internal:snk_read_master_valid
	signal read_mstr_internal_response_source_data       : std_logic_vector(255 downto 0); -- read_mstr_internal:src_response_data -> dispatcher_internal:snk_read_master_data
	signal read_mstr_internal_response_source_ready      : std_logic;                      -- dispatcher_internal:snk_read_master_ready -> read_mstr_internal:src_response_ready
	signal reset_n_reset_n_ports_inv                     : std_logic;                      -- reset_n_reset_n:inv -> [dispatcher_internal:reset, read_mstr_internal:reset]

begin

	dispatcher_internal : component dispatcher
		generic map (
			MODE                        => 1,
			RESPONSE_PORT               => 2,
			DESCRIPTOR_INTERFACE        => 0,
			DESCRIPTOR_FIFO_DEPTH       => 128,
			ENHANCED_FEATURES           => 0,
			DESCRIPTOR_WIDTH            => 128,
			DESCRIPTOR_BYTEENABLE_WIDTH => 16
		)
		port map (
			clk                     => clock_clk,                                                                                                                                                                                                                                                          --               clock.clk
			reset                   => reset_n_reset_n_ports_inv,                                                                                                                                                                                                                                          --         clock_reset.reset
			csr_writedata           => csr_writedata,                                                                                                                                                                                                                                                      --                 CSR.writedata
			csr_write               => csr_write,                                                                                                                                                                                                                                                          --                    .write
			csr_byteenable          => csr_byteenable,                                                                                                                                                                                                                                                     --                    .byteenable
			csr_readdata            => csr_readdata,                                                                                                                                                                                                                                                       --                    .readdata
			csr_read                => csr_read,                                                                                                                                                                                                                                                           --                    .read
			csr_address             => csr_address,                                                                                                                                                                                                                                                        --                    .address
			descriptor_write        => descriptor_slave_write,                                                                                                                                                                                                                                             --    Descriptor_Slave.write
			descriptor_waitrequest  => descriptor_slave_waitrequest,                                                                                                                                                                                                                                       --                    .waitrequest
			descriptor_writedata    => descriptor_slave_writedata,                                                                                                                                                                                                                                         --                    .writedata
			descriptor_byteenable   => descriptor_slave_byteenable,                                                                                                                                                                                                                                        --                    .byteenable
			src_read_master_data    => dispatcher_internal_read_command_source_data,                                                                                                                                                                                                                       -- Read_Command_Source.data
			src_read_master_valid   => dispatcher_internal_read_command_source_valid,                                                                                                                                                                                                                      --                    .valid
			src_read_master_ready   => dispatcher_internal_read_command_source_ready,                                                                                                                                                                                                                      --                    .ready
			snk_read_master_data    => read_mstr_internal_response_source_data,                                                                                                                                                                                                                            --  Read_Response_Sink.data
			snk_read_master_valid   => read_mstr_internal_response_source_valid,                                                                                                                                                                                                                           --                    .valid
			snk_read_master_ready   => read_mstr_internal_response_source_ready,                                                                                                                                                                                                                           --                    .ready
			csr_irq                 => csr_irq_irq,                                                                                                                                                                                                                                                        --             csr_irq.irq
			src_response_data       => open,                                                                                                                                                                                                                                                               --         (terminated)
			src_response_valid      => open,                                                                                                                                                                                                                                                               --         (terminated)
			src_response_ready      => '0',                                                                                                                                                                                                                                                                --         (terminated)
			snk_descriptor_data     => "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",                                                                                                                                 --         (terminated)
			snk_descriptor_valid    => '0',                                                                                                                                                                                                                                                                --         (terminated)
			snk_descriptor_ready    => open,                                                                                                                                                                                                                                                               --         (terminated)
			mm_response_waitrequest => open,                                                                                                                                                                                                                                                               --         (terminated)
			mm_response_byteenable  => "0000",                                                                                                                                                                                                                                                             --         (terminated)
			mm_response_address     => '0',                                                                                                                                                                                                                                                                --         (terminated)
			mm_response_readdata    => open,                                                                                                                                                                                                                                                               --         (terminated)
			mm_response_read        => '0',                                                                                                                                                                                                                                                                --         (terminated)
			src_write_master_data   => open,                                                                                                                                                                                                                                                               --         (terminated)
			src_write_master_valid  => open,                                                                                                                                                                                                                                                               --         (terminated)
			src_write_master_ready  => '0',                                                                                                                                                                                                                                                                --         (terminated)
			snk_write_master_data   => "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", --         (terminated)
			snk_write_master_valid  => '0',                                                                                                                                                                                                                                                                --         (terminated)
			snk_write_master_ready  => open                                                                                                                                                                                                                                                                --         (terminated)
		);

	read_mstr_internal : component read_master
		generic map (
			DATA_WIDTH                => 32,
			LENGTH_WIDTH              => 18,
			FIFO_DEPTH                => 32,
			STRIDE_ENABLE             => 0,
			BURST_ENABLE              => 0,
			PACKET_ENABLE             => 0,
			ERROR_ENABLE              => 1,
			ERROR_WIDTH               => 1,
			CHANNEL_ENABLE            => 1,
			CHANNEL_WIDTH             => 1,
			BYTE_ENABLE_WIDTH         => 4,
			BYTE_ENABLE_WIDTH_LOG2    => 2,
			ADDRESS_WIDTH             => 32,
			FIFO_DEPTH_LOG2           => 5,
			SYMBOL_WIDTH              => 8,
			NUMBER_OF_SYMBOLS         => 4,
			NUMBER_OF_SYMBOLS_LOG2    => 2,
			MAX_BURST_COUNT_WIDTH     => 1,
			UNALIGNED_ACCESSES_ENABLE => 0,
			ONLY_FULL_ACCESS_ENABLE   => 1,
			BURST_WRAPPING_SUPPORT    => 0,
			PROGRAMMABLE_BURST_ENABLE => 0,
			MAX_BURST_COUNT           => 1,
			FIFO_SPEED_OPTIMIZATION   => 1,
			STRIDE_WIDTH              => 1
		)
		port map (
			clk                  => clock_clk,                                     --            Clock.clk
			reset                => reset_n_reset_n_ports_inv,                     --      Clock_reset.reset
			master_address       => mm_read_address,                               -- Data_Read_Master.address
			master_read          => mm_read_read,                                  --                 .read
			master_byteenable    => mm_read_byteenable,                            --                 .byteenable
			master_readdata      => mm_read_readdata,                              --                 .readdata
			master_waitrequest   => mm_read_waitrequest,                           --                 .waitrequest
			master_readdatavalid => mm_read_readdatavalid,                         --                 .readdatavalid
			src_data             => st_source_data,                                --      Data_Source.data
			src_valid            => st_source_valid,                               --                 .valid
			src_ready            => st_source_ready,                               --                 .ready
			src_error            => st_source_error,                               --                 .error
			src_channel          => st_source_channel,                             --                 .channel
			snk_command_data     => dispatcher_internal_read_command_source_data,  --     Command_Sink.data
			snk_command_valid    => dispatcher_internal_read_command_source_valid, --                 .valid
			snk_command_ready    => dispatcher_internal_read_command_source_ready, --                 .ready
			src_response_data    => read_mstr_internal_response_source_data,       --  Response_Source.data
			src_response_valid   => read_mstr_internal_response_source_valid,      --                 .valid
			src_response_ready   => read_mstr_internal_response_source_ready,      --                 .ready
			master_burstcount    => open,                                          --      (terminated)
			src_sop              => open,                                          --      (terminated)
			src_eop              => open,                                          --      (terminated)
			src_empty            => open                                           --      (terminated)
		);

	reset_n_reset_n_ports_inv <= not reset_n_reset_n;

end architecture rtl; -- of soc_system_DMA_neurax_write
