# TCL File Generated by Component Editor 24.1
# Sat Feb 21 14:51:26 CET 2026
# DO NOT MODIFY


# 
# neurax_avalon_accelerator "neurax_accelerator" v1.0
# NAN 2026.02.21.14:51:26
# Neurax is a CNN accelerator
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module neurax_avalon_accelerator
# 
set_module_property DESCRIPTION "Neurax is a CNN accelerator"
set_module_property NAME neurax_avalon_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Neurax
set_module_property AUTHOR NAN
set_module_property DISPLAY_NAME neurax_accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL neurax
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file neurax.vhd VHDL PATH ../../hdl/neurax.vhd TOP_LEVEL_FILE
add_fileset_file FPGA_accelerator.vhd VHDL PATH ../../hdl/FPGA_accelerator.vhd
add_fileset_file activation_block.vhd VHDL PATH ../../hdl/activation_block.vhd
add_fileset_file convolution_block.vhd VHDL PATH ../../hdl/convolution_block.vhd
add_fileset_file neurax_accel_types_pkg.vhd VHDL PATH ../../hdl/neurax_accel_types_pkg.vhd
add_fileset_file neurax_data_interface.vhd VHDL PATH ../../hdl/neurax_data_interface.vhd
add_fileset_file neurax_register_pkg.vhd VHDL PATH ../../hdl/neurax_register_pkg.vhd
add_fileset_file pooling_block.vhd VHDL PATH ../../hdl/pooling_block.vhd
add_fileset_file neurax_register_block.vhd VHDL PATH ../../hdl/neurax_register_block.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL neurax
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file neurax.vhd VHDL PATH ../../hdl/neurax.vhd
add_fileset_file FPGA_accelerator.vhd VHDL PATH ../../hdl/FPGA_accelerator.vhd
add_fileset_file activation_block.vhd VHDL PATH ../../hdl/activation_block.vhd
add_fileset_file convolution_block.vhd VHDL PATH ../../hdl/convolution_block.vhd
add_fileset_file neurax_accel_types_pkg.vhd VHDL PATH ../../hdl/neurax_accel_types_pkg.vhd
add_fileset_file neurax_data_interface.vhd VHDL PATH ../../hdl/neurax_data_interface.vhd
add_fileset_file neurax_register_block.vhd VHDL PATH ../../hdl/neurax_register_block.vhd
add_fileset_file neurax_register_pkg.vhd VHDL PATH ../../hdl/neurax_register_pkg.vhd
add_fileset_file pooling_block.vhd VHDL PATH ../../hdl/pooling_block.vhd


# 
# parameters
# 
add_parameter g_WIDTH NATURAL 32
set_parameter_property g_WIDTH DEFAULT_VALUE 32
set_parameter_property g_WIDTH DISPLAY_NAME g_WIDTH
set_parameter_property g_WIDTH TYPE NATURAL
set_parameter_property g_WIDTH UNITS None
set_parameter_property g_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_WIDTH HDL_PARAMETER true
add_parameter g_ADDR_WIDTH NATURAL 4
set_parameter_property g_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property g_ADDR_WIDTH DISPLAY_NAME g_ADDR_WIDTH
set_parameter_property g_ADDR_WIDTH TYPE NATURAL
set_parameter_property g_ADDR_WIDTH UNITS None
set_parameter_property g_ADDR_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_ADDR_WIDTH HDL_PARAMETER true
add_parameter g_PIXEL_WIDTH NATURAL 24
set_parameter_property g_PIXEL_WIDTH DEFAULT_VALUE 24
set_parameter_property g_PIXEL_WIDTH DISPLAY_NAME g_PIXEL_WIDTH
set_parameter_property g_PIXEL_WIDTH TYPE NATURAL
set_parameter_property g_PIXEL_WIDTH UNITS None
set_parameter_property g_PIXEL_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_PIXEL_WIDTH HDL_PARAMETER true
add_parameter g_FB_WIDTH NATURAL 100
set_parameter_property g_FB_WIDTH DEFAULT_VALUE 100
set_parameter_property g_FB_WIDTH DISPLAY_NAME g_FB_WIDTH
set_parameter_property g_FB_WIDTH TYPE NATURAL
set_parameter_property g_FB_WIDTH UNITS None
set_parameter_property g_FB_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_FB_WIDTH HDL_PARAMETER true
add_parameter g_FB_HEIGHT NATURAL 100
set_parameter_property g_FB_HEIGHT DEFAULT_VALUE 100
set_parameter_property g_FB_HEIGHT DISPLAY_NAME g_FB_HEIGHT
set_parameter_property g_FB_HEIGHT TYPE NATURAL
set_parameter_property g_FB_HEIGHT UNITS None
set_parameter_property g_FB_HEIGHT ALLOWED_RANGES 0:2147483647
set_parameter_property g_FB_HEIGHT HDL_PARAMETER true
add_parameter PARALLEL_UNITS INTEGER 4
set_parameter_property PARALLEL_UNITS DEFAULT_VALUE 4
set_parameter_property PARALLEL_UNITS DISPLAY_NAME PARALLEL_UNITS
set_parameter_property PARALLEL_UNITS TYPE INTEGER
set_parameter_property PARALLEL_UNITS UNITS None
set_parameter_property PARALLEL_UNITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PARALLEL_UNITS HDL_PARAMETER true


# 
# display items
# 
add_display_item "" Register GROUP ""
add_display_item "" "RGB pixel" GROUP ""
add_display_item "" Framebuffer GROUP ""


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset g_rst_i reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk g_clk_i clk Input 1


# 
# connection point avalon_sink
# 
add_interface avalon_sink avalon_streaming end
set_interface_property avalon_sink associatedClock clk
set_interface_property avalon_sink associatedReset reset
set_interface_property avalon_sink dataBitsPerSymbol 8
set_interface_property avalon_sink errorDescriptor ""
set_interface_property avalon_sink firstSymbolInHighOrderBits true
set_interface_property avalon_sink maxChannel 0
set_interface_property avalon_sink readyLatency 0
set_interface_property avalon_sink ENABLED true
set_interface_property avalon_sink EXPORT_OF ""
set_interface_property avalon_sink PORT_NAME_MAP ""
set_interface_property avalon_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_sink g_asi_channel_i channel Input 1
add_interface_port avalon_sink g_asi_data_i data Input "((g_width-1)) - (0) + 1"
add_interface_port avalon_sink g_asi_error_i error Input 1
add_interface_port avalon_sink g_asi_valid_i valid Input 1
add_interface_port avalon_sink g_asi_ready_o ready Output 1


# 
# connection point avalon_source
# 
add_interface avalon_source avalon_streaming start
set_interface_property avalon_source associatedClock clk
set_interface_property avalon_source associatedReset reset
set_interface_property avalon_source dataBitsPerSymbol 8
set_interface_property avalon_source errorDescriptor ""
set_interface_property avalon_source firstSymbolInHighOrderBits true
set_interface_property avalon_source maxChannel 0
set_interface_property avalon_source readyLatency 0
set_interface_property avalon_source ENABLED true
set_interface_property avalon_source EXPORT_OF ""
set_interface_property avalon_source PORT_NAME_MAP ""
set_interface_property avalon_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_source g_aso_channel_o channel Output 1
add_interface_port avalon_source g_aso_data_o data Output "((g_width-1)) - (0) + 1"
add_interface_port avalon_source g_aso_error_o error Output 1
add_interface_port avalon_source g_aso_valid_o valid Output 1
add_interface_port avalon_source g_aso_ready_i ready Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 g_avs_address_i address Input "((g_addr_width-1)) - (0) + 1"
add_interface_port avalon_slave_0 g_avs_byteenable_i byteenable Input "(((g_width/8)-1)) - (0) + 1"
add_interface_port avalon_slave_0 g_avs_chipselect_i chipselect Input 1
add_interface_port avalon_slave_0 g_avs_read_i read Input 1
add_interface_port avalon_slave_0 g_avs_write_i write Input 1
add_interface_port avalon_slave_0 g_avs_writedata_i writedata Input "((g_width-1)) - (0) + 1"
add_interface_port avalon_slave_0 g_avs_readdata_o readdata Output "((g_width-1)) - (0) + 1"
add_interface_port avalon_slave_0 g_avs_readdatavalid_o readdatavalid Output 1
add_interface_port avalon_slave_0 g_avs_waitrequest_o waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

