# TCL File Generated by Component Editor 24.1
# Mon Sep 22 20:53:46 CEST 2025
# DO NOT MODIFY


# 
# neurax_avalon_accelerator "neurax_accelerator" v1.0
# NAN 2025.09.22.20:53:46
# Neurax is a CNN accelerator
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module neurax_avalon_accelerator
# 
set_module_property DESCRIPTION "Neurax is a CNN accelerator"
set_module_property NAME neurax_avalon_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Neurax
set_module_property AUTHOR NAN
set_module_property DISPLAY_NAME neurax_accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL neurax
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file neurax.vhd VHDL PATH ../../hdl/neurax.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL neurax
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file neurax.vhd VHDL PATH ../../hdl/neurax.vhd


# 
# parameters
# 
add_parameter g_WIDTH NATURAL 32 "Word width"
set_parameter_property g_WIDTH DEFAULT_VALUE 32
set_parameter_property g_WIDTH DISPLAY_NAME g_WIDTH
set_parameter_property g_WIDTH TYPE NATURAL
set_parameter_property g_WIDTH ENABLED false
set_parameter_property g_WIDTH UNITS None
set_parameter_property g_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_WIDTH DESCRIPTION "Word width"
set_parameter_property g_WIDTH HDL_PARAMETER true
add_parameter g_ADDR_WIDTH NATURAL 3 " Addres width"
set_parameter_property g_ADDR_WIDTH DEFAULT_VALUE 3
set_parameter_property g_ADDR_WIDTH DISPLAY_NAME g_ADDR_WIDTH
set_parameter_property g_ADDR_WIDTH TYPE NATURAL
set_parameter_property g_ADDR_WIDTH ENABLED false
set_parameter_property g_ADDR_WIDTH UNITS None
set_parameter_property g_ADDR_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_ADDR_WIDTH DESCRIPTION " Addres width"
set_parameter_property g_ADDR_WIDTH HDL_PARAMETER true
add_parameter g_PIXEL_WIDTH NATURAL 24 "24-bit RGB pixel"
set_parameter_property g_PIXEL_WIDTH DEFAULT_VALUE 24
set_parameter_property g_PIXEL_WIDTH DISPLAY_NAME g_PIXEL_WIDTH
set_parameter_property g_PIXEL_WIDTH TYPE NATURAL
set_parameter_property g_PIXEL_WIDTH UNITS None
set_parameter_property g_PIXEL_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_PIXEL_WIDTH DESCRIPTION "24-bit RGB pixel"
set_parameter_property g_PIXEL_WIDTH HDL_PARAMETER true
add_parameter g_FB_WIDTH NATURAL 100 "Framebuffer width"
set_parameter_property g_FB_WIDTH DEFAULT_VALUE 100
set_parameter_property g_FB_WIDTH DISPLAY_NAME g_FB_WIDTH
set_parameter_property g_FB_WIDTH TYPE NATURAL
set_parameter_property g_FB_WIDTH UNITS None
set_parameter_property g_FB_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property g_FB_WIDTH DESCRIPTION "Framebuffer width"
set_parameter_property g_FB_WIDTH HDL_PARAMETER true
add_parameter g_FB_HEIGHT NATURAL 100 "Framebuffer heigth"
set_parameter_property g_FB_HEIGHT DEFAULT_VALUE 100
set_parameter_property g_FB_HEIGHT DISPLAY_NAME g_FB_HEIGHT
set_parameter_property g_FB_HEIGHT TYPE NATURAL
set_parameter_property g_FB_HEIGHT UNITS None
set_parameter_property g_FB_HEIGHT ALLOWED_RANGES 0:2147483647
set_parameter_property g_FB_HEIGHT DESCRIPTION "Framebuffer heigth"
set_parameter_property g_FB_HEIGHT HDL_PARAMETER true


# 
# display items
# 
add_display_item Register g_WIDTH PARAMETER ""
add_display_item Register g_ADDR_WIDTH PARAMETER ""
add_display_item "RGB pixel" g_PIXEL_WIDTH PARAMETER ""
add_display_item Framebuffer g_FB_WIDTH PARAMETER ""
add_display_item Framebuffer g_FB_HEIGHT PARAMETER ""


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_i reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_i clk Input 1


# 
# connection point avalon_sink
# 
add_interface avalon_sink avalon_streaming end
set_interface_property avalon_sink associatedClock clk
set_interface_property avalon_sink associatedReset reset
set_interface_property avalon_sink dataBitsPerSymbol 8
set_interface_property avalon_sink errorDescriptor ""
set_interface_property avalon_sink firstSymbolInHighOrderBits true
set_interface_property avalon_sink maxChannel 0
set_interface_property avalon_sink readyLatency 0
set_interface_property avalon_sink ENABLED true
set_interface_property avalon_sink EXPORT_OF ""
set_interface_property avalon_sink PORT_NAME_MAP ""
set_interface_property avalon_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_sink asi_channel_i channel Input 1
add_interface_port avalon_sink asi_data_i data Input "((g_width-1)) - (0) + 1"
add_interface_port avalon_sink asi_valid_i valid Input 1
add_interface_port avalon_sink asi_error_i error Input 1
add_interface_port avalon_sink asi_ready_o ready Output 1


# 
# connection point avalon_source
# 
add_interface avalon_source avalon_streaming start
set_interface_property avalon_source associatedClock clk
set_interface_property avalon_source associatedReset reset
set_interface_property avalon_source dataBitsPerSymbol 8
set_interface_property avalon_source errorDescriptor ""
set_interface_property avalon_source firstSymbolInHighOrderBits true
set_interface_property avalon_source maxChannel 0
set_interface_property avalon_source readyLatency 0
set_interface_property avalon_source ENABLED true
set_interface_property avalon_source EXPORT_OF ""
set_interface_property avalon_source PORT_NAME_MAP ""
set_interface_property avalon_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_source aso_data_o data Output "((g_width-1)) - (0) + 1"
add_interface_port avalon_source aso_valid_o valid Output 1
add_interface_port avalon_source aso_channel_o channel Output 1
add_interface_port avalon_source aso_error_o error Output 1
add_interface_port avalon_source aso_ready_i ready Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_readdata_o readdata Output "((g_width-1)) - (0) + 1"
add_interface_port avalon_slave avs_readdatavalid_o readdatavalid Output 1
add_interface_port avalon_slave avs_waitrequest_o waitrequest Output 1
add_interface_port avalon_slave avs_address_i address Input "((g_addr_width-1)) - (0) + 1"
add_interface_port avalon_slave avs_byteenable_i byteenable Input "(((g_width/8)-1)) - (0) + 1"
add_interface_port avalon_slave avs_chipselect_i chipselect Input 1
add_interface_port avalon_slave avs_read_i read Input 1
add_interface_port avalon_slave avs_write_i write Input 1
add_interface_port avalon_slave avs_writedata_i writedata Input "((g_width-1)) - (0) + 1"
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

