# NEURAX Software Makefile

# Default target
.PHONY: all clean dev

all:
	$(MAKE) -C lib all

dev:
	$(MAKE) -C lib dev

clean:
	$(MAKE) -C lib clean

install:
	$(MAKE) -C lib install

uninstall:
	$(MAKE) -C lib uninstall

help:
	$(MAKE) -C lib help
